# Site settings
title: "cmalaitai"
bye_message: "Ka kite!"
baseurl: "/"
url: "https://cmalaitai.github.io"
disqus: gjuniioor

# Header settings
nick: "cmalaitai"
mail:
    domain: "protonmail"
    ext: "ch"
source_code:
    server: "github.com"
    nick: "cmalaitai"
blog:
    server: "wordpress.com"
    nick: "cmalaitai"
fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
